### ISSUE TITLE
Library not importing

### ISSUE THREAD

**Issue by spung** [tvbarthel/BlurDialogFragment#34]
Not sure if that's the best title, but I'm trying to integrate this with my project. I put the following line into my project specific gradle dependencies: 
compile 'fr.tvbarthel.blurdialogfragment:lib:2.1.2'

Then I sync gradle, wait for that to finish, and try to import BlurDialogFragment or SupportBlurDialogFragment with no luck. I haven't had any issues integrating with other open source libraries recently. Are there any other requirements/quirks I should be aware of when using this?

Thanks

**Comment by tbarthel-fr** [comment]
Hi @spung (:

Since the library has been promoted to jcenter(), no other requirements are needed to use this project.

In your Project/build.gradle, are you using jcenter ? : 

```java
...
allprojects {
    repositories {
        jcenter()
    }
}
....
```

Then in your Project/appModule/build.gradle : 

```java
dependencies {
    ...
    compile 'fr.tvbarthel.blurdialogfragment:lib:2.1.4'
    ...
}
```

If gradle couldn't find the dependency, it must fail during sync.

I have no other idea for the moment (I presume you already tried a ./gradlew clean). 

Which version of Android Studio are you using ?

**Comment by spung** [comment]
It's working now @tbarthel-fr , looks like I was stuck in a weird state switching to jcenter from maven and a ./gradlew clean and cleaning the project did it. Thanks for your help!

**Comment by tbarthel-fr** [comment]
Glad to read that it works now (:

Happy coding (= !

**Comment by spung** [comment]
Thanks again, cheers :)
