### ISSUE TITLE
BlurDialogEngine onDestroy will be crash

### ISSUE THREAD

**Issue by h3clikejava** [tvbarthel/BlurDialogFragment#44]
at line 78 in BlurDialogEngine.java
" this.mBluringTask.cancel(true);"
the mBuluringTask will be null, so will null point exception

**Comment by eefret** [comment]
For anyone interested here's the stacktrace

```
10-06 10:49:42.072 30956-30956/com.bebler.app E/AndroidRuntime: FATAL EXCEPTION: main
10-06 10:49:42.072 30956-30956/com.bebler.app E/AndroidRuntime: Process: com.bebler.app, PID: 30956
10-06 10:49:42.072 30956-30956/com.bebler.app E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$BlurAsyncTask.cancel(boolean)' on a null object reference
```

**Comment by tbarthel-fr** [comment]
Hi (=

first of all thanks a lot for your feedback.

This issue should have been fixed by @tommytcchan in his PR:
https://github.com/tvbarthel/BlurDialogFragment/pull/42

As the AsyncTask was created inside the onResume, a NPE could have been thrown if something cause the dialog.onDestroy() to be called before the resume callback.

I will close this issue once a new version of the library will be published.

Thanks you!
