### ISSUE TITLE
Lib size

### ISSUE THREAD

**Issue by PingForward** [tvbarthel/BlurDialogFragment#61]
Hi there.

Why library is so heavy?? [Dependencies JAR size (KB) 2094](http://www.methodscount.com/?lib=fr.tvbarthel.blurdialogfragment%3Alib%3A2.1.6)
Or dependencies size is doesn’t meter?

**Comment by tbarthel-fr** [comment]
Hi @PingForward (=

Library weight as well as method count is one of our priority when we try to release some of our work as open source.

Regarding the BlurDialogFragment project and based on your link : 
* Methods count : 211;
* JAR Size  : 35KB;
* DEX size : 24KB;

From our point of view these numbers are acceptable and won't impact the size of your apk neither the method limit as much. As the project is open source, we didn't tried to reduce the method count more than needed to keep a balance between maintainability and number of method (basically, we always try to avoid a single method to perfom all the expected behavior just to have a method count artificially low).

Now, as you mentionned, the library has dependencies, which increase the impact of using BlurDialogFragment on your final apk. These dependencies are the following : 
* com.android.support:appcompat-v7:23.1.1 (Methods count: 5319, Size: 902 KB)
* com.android.support:support-annotations:23.1.1 (Methods count: 20, Size: 20KB)
* com.android.support:support-v4:23.1.1 (Methods count: 8914, Size: 1174 KB)


As these dependencies are used let's say 90+% of the time (am I wrong?), they already impact your apk even if you don't include blurdialogfragment. Therefore we didn't try to split the library into several part. 

Would you be interested in a split such as ? 
* fr.tvbarthel.blurdialogfragment:core:2.1.6 (only pur java code)
* fr.tvbarthel.blurdialogfragment:compat:2.1.6 (android compat dependencies)
* fr.tvbarthel.blurdialogfragment:support:2.1.6 (android support dependencies)

We are currently considering this question for a new project that we have just released last week. Most of developers' feedback were : "these libraries are light enough and proguard will remove un-needed code from dependencies for a release build". We are going to try to get more feedback on reddit, maybe you could give us yours here (:
