### ISSUE TITLE
I can  not capture the screen when a video is playing

### ISSUE THREAD

**Issue by woniu0936** [tvbarthel/BlurDialogFragment#67]
is it bug？

**Comment by woniu0936** [comment]
when a video is playing, BlurDialogFragment can not get the ScreenShot

**Comment by woniu0936** [comment]
seems the SurfaceView's bitmap can't be captrued. It's really nice if you can help check it.

**Comment by tbarthel-fr** [comment]
Hi (=

Background bitmap is created thanks to View.XXXDrawingCache() set of methods : 
https://github.com/tvbarthel/BlurDialogFragment/blob/master/lib/src/main/java/fr/tvbarthel/lib/blurdialogfragment/BlurDialogEngine.java#L568

Unfortunatelly, the surface part of the surfaceView is rendered bellow the window in a complete separate layer. This means that buildDrawingCache won't get the surface pixel.
https://developer.android.com/reference/android/view/SurfaceView.html

To get surface pixels of a SurfaceView you could try to play with the lockCanvas set of methods as explained here: 
http://stackoverflow.com/questions/27817577/android-take-screenshot-of-surface-view-shows-black-screen

You could also replace your SurfaceView by a TextureView and use getBitmap().

Anyway, currently their is no callback allowing you to draw additionnal elements on the bitmap retrieved from the drawing cache... 

I'm going to check if buildDrawingCache can be easilly overriden or caught so that you could draw the content of a Texture/SurfaceView manually.

**Comment by woniu0936** [comment]
think you very much

**Comment by tbarthel-fr** [comment]
@woniu0936 
just for the science, we successfully blur the preview of a camera, which is using a TextureView.

It's technically possible without tweaking the library, just by wrapping your TextureView in a custom FrameLayout which correctly override drawChild and dispatchDraw.
