### ISSUE TITLE
[Feature request] Fade in / Fade out animation

### ISSUE THREAD

**Issue by jacobtabak** [tvbarthel/BlurDialogFragment#8]
It would be nice for an optional fade in / fade out animation.  When the blurred view is added, it's almost unpleasant without a fade.  If you're interested I have a working implementation I could make into a PR but it's API 11+.

**Comment by tbarthel-fr** [comment]
Hi @jacobtabak 

Thanks a lot for your interest! 

We totally agree with you for the needs of a fade in / fade out animation (=

I started a first implementation on the "animate-attempt" branch of the repo.

Could you make a PR of your work or simply publish it in order to compare the two implementations ?
